---
include:
  - board: nice_nano_v2
    shield: scylla_left
    snippet: studio-rpc-usb-uart
    snippet: cdc-acm-console
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: scylla_right
    snippet: cdc-acm-console

